version: '3'
services:
  database:
    build: ./database
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - database
    user: root
    command: /bin/bash -c "python backend.py"